# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51a2e068ffa6efde70b1eb9fd5bf4212"
name = "PayMongo Gateway"
application_url = "https://shopify-webhook-3.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_customers,write_customers,read_products"


[auth]
redirect_urls = [ "https://shopify-webhook-3.onrender.com/auth/callback" ]
